#!/bin/bash
echo "=== Deadlight VPN Diagnostic ==="
echo ""
echo "1. TUN device status:"
ip addr show tun0 2>/dev/null || echo "   tun0 not found"
echo ""
echo "2. Routing table:"
ip route | grep tun0 || echo "   No routes through tun0"
echo ""
echo "3. Is Deadlight listening?"
ps aux | grep deadlight | grep -v grep
echo ""
echo "4. lwIP status (check Deadlight logs for):"
echo "   - 'VPN: Raw TCP listener configured'"
echo "   - 'VPN: Gateway initialized successfully'"
echo ""
echo "5. Test packet injection:"
echo "   Run: sudo tcpdump -i tun0 -n &"
echo "   Run: sudo hping3 -S -p 80 -c 1 93.184.216.34 --interface tun0"
echo "   You should see packets in tcpdump AND VPN logs"
