// src/ui/assets.h
#ifndef ASSETS_H
#define ASSETS_H

// Embedded UI assets (generated by xxd in assets.c)
extern unsigned char src_ui_index_html[];
extern unsigned int src_ui_index_html_len;

extern unsigned char src_ui_favicon_ico[];
extern unsigned int src_ui_favicon_ico_len;

extern unsigned char src_ui_favicon_png[];
extern unsigned int src_ui_favicon_png_len;

#endif // ASSETS_H